### ISSUE TITLE
--events for all scans

### ISSUE THREAD

**Issue by jstanley23** [zenoss/zenoss.toolbox#101]
Can you please add --events for all scans. This would be huge help.

**Comment by burbel** [comment]
Jay -     ZEN-21414
All tools should support --events like zencatalogscan

Don't have an ETA but it's now in the toolbox backlog, which I do hope to get to shortly.

**Comment by jstanley23** [comment]
Thanks Brian. I would like to run the tools a few times a week and then create tickets from any errors.

**Comment by burbel** [comment]
This has been added to the dev version of the toolbox for findposkeyerror, zenrelationscan, and zencatalogscan.  Going to examine the other tools tomorrow, but since the main tools are now all in here, marking this closed.  New toolbox official release coming soon.
