### ISSUE TITLE
is there going to be a new official release soon

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss.toolbox#121]
device search being fixed would help me..was wondering when you are releasing the next version of the toolbox?

**Comment by burbel** [comment]
Doug, I don't believe the device-level catalogs will make the next toolbox release, but work is ongoing.

**Comment by burbel** [comment]
Doug, a new release went out a few days ago, including associated updates to the KB articles.

**Comment by dougsyer** [comment]
Thanks i got it
