### ISSUE TITLE
Mib scanner.

### ISSUE THREAD

**Issue by Serpent6877** [zenoss/zenoss.toolbox#36]
There is a error in the scanning of the Mibs:

zencatalogscan.py line 196:

'Mibs.mibsearch': 'dmd.Mibs.mibsearch',

should be:

'Mibs.mibSearch': 'dmd.Mibs.mibSearch',

But this still does not find the error I am receiving in Zenoss of:

KeyError: '/zport/dmd/Mibs/SentryCDU' 

This error occured after a failed install of the SentryCDU zenpack. It crashed on the CLI install but still showed up in Zenoss as an installed zenpack. Before and after removal I now get the keyerror.

**Comment by burbel** [comment]
Version 0.5.2 includes the fix for this issue.
