### ISSUE TITLE
zenreindextool conflicts

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss.toolbox#38]
I think there may be an issue with syncs/retries/commits when you run the reindex tool.  i havent looked at it, not sure how often its committing but so far I havent seen it be able to get through our devices without a conflict error (normal one not those crazy time ones).

**Comment by burbel** [comment]
Doug, since my testing of the tools is done against an idle system, a question - there is a dmd.syncdb() call that I can generate, but I noticed from your change on pull #39 the inclusion of the _p_jar.sync() calls.  Are both of these required?
