### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss.toolbox#82]
quick question,

will the toolbox tools detect if the zodb entry for a catalog has problems.  ie you have a catalog object stranded at the devices level?

Doug

**Comment by burbel** [comment]
Doug, zencatalogscan does nothing with device-level catalogs.  In terms of something potentially orphaned, however, zenossdbpack would likely clean that up.  I'm not exactly sure what you mean by stranded in your question.

**Comment by dougsyer** [comment]
sorry i mean say a zenpack creates a catalog object in the zodb under a device class somewhere.  assuming for simplicity there are no entries in the catalog..IM assuming its possible for the catalog reference object(not sure the term) can have a poskey?

**Comment by burbel** [comment]
It is entirely possible for that, and I believe zodbscan would detect it - it's possible that findposkeyerror would as well, but findposkeyerror and the method it takes to traverse the tree does skip a large number of objects.  Right now zencatalogscan does no searching for any catalogs off of devices.  I have two future enhancements, one to fix your two outstanding issues with ZenPacks that add per-device catalogs, and another to scan through an entire zodb for all objects of type catalog, to help detect all of these.

Ideally, once we had that list, we could then do an extensive zencatalogscan of all catalogs.  At least that is my thought/plan.  But that is still far in the future.

**Comment by dougsyer** [comment]
okay.  thank..
