### ISSUE TITLE
0.8.1 findposkey not fixing _snmp uptime?

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss.toolbox#88]
I ran fix = true on findposkeyerror but it looks like either the fix counter didnt increment or it didnt try to fix the snmp uptime issues.  I know how to manually fix those but i'm not sure if you are aware of this, i didnt look to see if this was fixed with later commits.

2015-10-01 09:53:00,529 INFO findposkeyerror: Examining items under the '/' path (<Application at >)
2015-10-01 09:53:00,529 INFO findposkeyerror: ## Beginning cycle 1 of 2 (potential)
2015-10-01 09:57:20,911 CRITICAL findposkeyerror: AttributeError: 'ZenStatus' object has no attribute 'getStatus' on attribute '_lastPollSnmpUpTime' of /zport/dmd/Devices/REMOVED
2015-10-01 11:07:26,510 INFO findposkeyerror: findposkeyerror cycle 1: examined REMOVED objects, encountered 6 errors, and attempted 0 repairs
2015-10-01 11:07:26,510 INFO findposkeyerror: findposkeyerror completed in REMOVED seconds
2015-10-01 11:07:26,510 INFO findposkeyerror: ############################################################

**Comment by dougsyer** [comment]
I went in and ran it again against just a subset of objects that were showing the ZenStatus issue and looks like it still didnt try to fix them.  I did cycles = 5 this time with the -f to be sure that wasnt the issue.

When I tried to run cycles = 5 looks like it didnt cycle(I think maybe that was fixed in the latest dev..

[zenoss@IMAX-ZNS-ZEO-003 tmp]$ findposkeyerror -u -f -n 5 -p dmd.Devices.vSphere.vCenters

[2015-10-01 11:57:40] Initializing findposkeyerror version 1.8.1 (detailed log at /opt/zenoss/log/toolbox/findposkeyerror.log)

[2015-10-01 11:57:51] Examining items under the 'dmd.Devices.vSphere.vCenters' path (<DeviceClass at vCenters>):

[2015-10-01 11:59:26]  Cycle 1  | Items Scanned:       REMOVED | Errors:       2 | Repairs:      0 |

[2015-10-01 11:59:26] Execution finished in 0:01:46

**Comment by dougsyer** [comment]
wht is strange is that when i go into dmd, i dont get a poskey error when i do this:

>>> d=find('DEVICEHAVINGISSUES')
>>> d.getStatus()
0

**Comment by dougsyer** [comment]
okay i went in an just reset the OOBTree and in dmd it seems fine although findposkey still sees it an an error.

I an open a regular support ticket on this but I wanted to see if there isnt a know issue with the toolbox first.

some of the examples here were from vSpheres but i have a few windows devices that seem fine but ..not sure if this means there is an OOB tree stranded somewhere but the devices seem okay.

>>> d._lastPollSnmpUpTime
<ZenStatus.ZenStatus object at 0xbedfc80>
>>> d._lastPollSnmpUpTime.getStatus()
0

**Comment by dougsyer** [comment]
by reset I mean I did this procedure:

d = find('BLAH')
from ZenStatus import ZenStatus
from BTrees.OOBTree import OOSet
d._delOb('_lastPollSnmpUpTime')
commit()

**Comment by burbel** [comment]
Doug, thanks for all of this information, and almost certainly this was introduced with the newer FPKE script.  In my local testing I didn't encounter this issue, but a couple of other customers have cases pending for this item, as well.  The logic in that section is trying to use the call to see if the attribute exists and is working as expected, but this particular failure case is apparently a flaw in that logic.

Would it be possible to get a copy of your zodb via Leapfile so I can investigate locally?

**Comment by burbel** [comment]
Doug, if you have a moment, can I please get you to test a modified fpke and see what results you get?  If you have a sandbox with this backed up, that would be best.

Download the current findposkeyerror.py file, and change line 268 from
except POSKeyError as pke:
to
except ( POSKeyError, AttributeError ) as fixableException:

Please make sure to keep the indentation to match as before.  To execute, as the zenoss user, just type 'python findposkeyerror.py -v10' with this file, and it will run through and find the impacted devices.  If you are feeling brave, you can then run with the -f flag to fix the issues.

I have a different zenrestore in-house that was exhibiting these issues, and making this change was sufficient to address the 4 issues that they had.  I haven't finished testing and reviewing this change, but if you have a sandbox, would love your feedback.

**Comment by dougsyer** [comment]
Okay i can try it next week.

**Comment by dougsyer** [comment]
By the way wasnt sure if this wss clear but manually resetting the zenstatus didnt stop a new scan from reporting the error.

i tried getstatus on the devicrd and i dont get a poskey exception in dmd

**Comment by burbel** [comment]
Doug, I saw the same thing internally - I’m not 100% sure what is at play here, why via zendmd the command seems to work successfully, and fails in findposkeyerror, but with this one-line change after doing a fix we do not see the error again.  

Hence me not wanting to test against PROD and wanting to get more feedback before I put this change in.

**Comment by dougsyer** [comment]
Okay thanks.  Ill see if there is any common thread to the devices in question.

**Comment by dougsyer** [comment]
Actually i stumbled into a similar thing with attribute errors this week amd I still dont understand it.  I could reproduce a behavior that is very similar to this attribute error behavior you are seeing..i thjnk..ill try it this weekend and post it

**Comment by dougsyer** [comment]
this may be totally irrelevant but it is something that is interesting, i had no idea about and something I have to keep in mind if im dealing with a corner case..

when I look at components it seems other components show up with a relation on other components.  it looks like since _relations is a "class property" it calls and through (acquisition?)  it will see the power supply relation from device.hw on a power supply object.

*** d is a cisco device but it doesnt really matter what class it is***
>>> d=find('MYSWITCH')
>>> d
<CiscoDevice at /zport/dmd/Devices/Network/Cisco/blah path blah devices/MYSWITCH>

*** f is fan ***

>>> f=d.hw.fans()[0]
>>> f
<CiscoDevice at /zport/dmd/Devices/Network/Cisco/blah path blah/devices/MYSWITCH/hw/fans/Fan>

*** f has a power supplies method but not in _relations***

>>> for a, b in f._relations:  print a, b
...
dependencies <Products.ZenRelations.RelSchema.ToMany instance at 0x11a00e18>
dependents <Products.ZenRelations.RelSchema.ToMany instance at 0x11a00ef0>
maintenanceWindows <Products.ZenRelations.RelSchema.ToManyCont instance at 0x11a00f38>
productClass <Products.ZenRelations.RelSchema.ToOne instance at 0x12337638>
hw <Products.ZenRelations.RelSchema.ToOne instance at 0x152a4c68>

>>> getattr(f, 'powersupplies')
<ToManyContRelationship at /zport/dmd/Devices/Network/Cisco/Switch/4500/devices/WMASW1/hw/powersupplies used for /zport/dmd/Devices/Network/Cisco/Switch/4500/devices/WMASW1/hw/fans/Fan>

**** there is a relation for ciscodevice called voltage sensors fan can see that too ***

>>> for a, b in d._relations:  print a, b
...
blah blah blah..relations...blah blah...
voltagesensors <Products.ZenRelations.RelSchema.ToManyCont instance at 0x1349e9e0>
>>> f.voltagesensors()
[]

**Comment by dougsyer** [comment]
I think i see the line you asked me to change as line # 346?

**Comment by burbel** [comment]
Doug, my apologies, that's completely correct, line 346.  My local version is a sandbox where I am taking common utilities for the toolbox into a utilities file to avoid code duplication between scripts, and findposkeyerror was my first test.

**Comment by burbel** [comment]
Doug, I have tested this at two other environments, and pushed an updated version of the toolbox to master with this change, toolbox version 0.8.1.  Please test (or run 0.8.1) and let me know if there are any issues.  Going to close this for the meantime as fixed.
